script:
  - docker --version # print the version for logging
  - docker build ./feed -t udagram-feed -f feed/Dockerfile
  - docker tag udagram-feed khalidhisham10/udagram-feed:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push khalidhisham10/udagram-feed:latest