script:
  - docker --version # print the version for logging
  - docker build ./reverse -t udagram-reverse-proxy -f reverse/Dockerfile
  - docker tag udagram-reverse-proxy khalidhisham10/udagram-reverse-proxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push khalidhisham10/udagram-reverse-proxy:latest