apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-user
  name: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-user
  template:
    metadata:
      labels:
        service: udagram-user
    spec:
      containers:
      - image: khalidhisham10/udagram-user
        name: udagram-user
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_USERNAME
                name: env-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PASSWORD
                name: env-config          
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: env-config  
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_HOST
                name: env-config
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                key: AWS_REGION
                name: env-config
          - name: AWS_PROFILE
            valueFrom:
                configMapKeyRef:
                  key: AWS_PROFILE
                  name: env-config
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                key: AWS_BUCKET
                name: env-config
          - name: JWT_SECRET
            valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: env-config
          - name: URL
            valueFrom:
              configMapKeyRef:
                key: URL
                name: env-config    
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always